/*
 * DO NOT EDIT THIS FILE
 */

public class BSTNode{

    /*
    * Class for node of a BST.
    */

    public int value, height;
    public BSTNode left, right;

    public BSTNode(int value){
        /*
        * DO NOT EDIT THIS FUNCTION
        */
        this.value = value;
        this.height = 1;
        this.left = null;
        this.right = null;
    }
}
